backend:
  name: github
  repo: threenine/rea-intelligence

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
    - name: "posts"
      label: "Posts"
      folder: "static/posts"
      create: true
      slug: "{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Summary", name: "summary", widget: "string"}
          - label: "Author"
            name: "author"
            widget: "relation"
            collection: "Authors"
            search_fields: [ "name.firstName" , "name.lastName" ]
            value_field: "title"
            display_fields: [ "name.firstName" , "name.lastName" ]
          - {label: "Keywords", name: "Keywords", widget: "string" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "date"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Tags"
            name: "tags"
            widget: list
            field: { label: "Tag", name: "tag", widget: "string" }
    - name: "crypto"
      label: "Crypto"
      folder: "static/guides/crypto"
      create: true
      slug: "{{slug}}"
      fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Description", name: "description", widget: "string"}
         - {label: "Publish Date", name: "date", widget: "date"}
         - {label: "Body", name: "body", widget: "markdown"}

    - name: "Authors"
      label: "Authors"
      folder: "static/authors"
      create: true
      slug: "{{slug}}"
      fields:
      - {label: "Github Username", name: "title", widget: "string", required: true, hint: "Github username" }
      -  label: "Full name"
         name: "name"
         widget: "object"
         fields:
             - {label: "Firstname", name: "firstName", widget: "string", required: true}
             - {label: "Lastname", name: "lastName", widget: "string", required: true }
